name: dmv
description: "DMV بالعربي — Arabic-first US driving license exam simulator."
publish_to: 'none'
version: 1.0.4+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.5
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  connectivity_plus: ^6.1.5
  flutter_stripe: ^13.1.0
  audioplayers: ^6.8.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^22.2.0
  in_app_purchase: ^3.3.0
  in_app_purchase_storekit: ^0.4.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/logo/
    - assets/sounds/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
