/// English string map. Keys must match [StringsAr].
const Map<String, String> stringsEn = {
  'app.name': 'DMV in Arabic',
  'app.tagline': 'Prepare for your driving license test',

  'common.ok': 'OK',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.save': 'Save',
  'common.close': 'Close',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.skip': 'Skip',
  'common.loading': 'Loading...',
  'common.retry': 'Retry',
  'common.error': 'Error',
  'common.success': 'Success',
  'common.or': 'or',
  'common.required': 'Required',
  'common.optional': 'Optional',

  'auth.login.title': 'Sign In',
  'auth.login.subtitle': 'Welcome back',
  'auth.login.submit': 'Sign In',
  'auth.login.no_account': "Don't have an account?",
  'auth.login.sign_up': 'Sign Up',
  'auth.login.forgot': 'Forgot password?',

  'auth.register.title': 'Create Account',
  'auth.register.subtitle': 'Join now and start practicing',
  'auth.register.submit': 'Create Account',
  'auth.register.have_account': 'Already have an account?',
  'auth.register.sign_in': 'Sign In',

  'auth.verify.title': 'Verify Your Identity',
  'auth.verify.subtitle': 'Enter the code sent to',
  'auth.verify.submit': 'Verify',
  'auth.verify.resend': 'Resend Code',
  'auth.verify.resend_in': 'Resend in',
  'auth.verify.expires_in': 'Code expires in',
  'auth.verify.expired': 'Code expired',
  'auth.verify.max_resends': 'You have reached the maximum resend limit (3/hour).',

  'auth.forgot.title': 'Forgot Password',
  'auth.forgot.subtitle': 'Enter your email or phone to reset your password',
  'auth.forgot.submit': 'Send Recovery Code',
  'auth.forgot.back_login': 'Back to Sign In',

  'auth.reset.title': 'Reset Password',
  'auth.reset.subtitle': 'Enter the code and your new password',
  'auth.reset.submit': 'Set New Password',

  'auth.social.google': 'Continue with Google',
  'auth.social.apple': 'Continue with Apple',
  'auth.social.unavailable': 'Social login is not available yet.',

  'auth.logout': 'Sign Out',
  'auth.logout.confirm': 'Are you sure you want to sign out?',

  'field.name': 'Full Name',
  'field.email': 'Email',
  'field.phone': 'Phone Number',
  'field.email_or_phone': 'Email or Phone Number',
  'field.password': 'Password',
  'field.confirm_password': 'Confirm Password',
  'field.code': 'Verification Code',
  'field.new_password': 'New Password',

  'error.network': 'No internet connection. Please check your network.',
  'error.server': 'Server error. Please try again later.',
  'error.timeout': 'Request timed out. Check your connection.',
  'error.unauthorized': 'Session expired. Please sign in again.',
  'error.storage': 'Secure storage error. You will be signed out.',
  'error.unknown': 'An unexpected error occurred. Please try again.',

  'home.greeting': 'Signed in successfully',
  'home.welcome': 'Welcome to DMV in Arabic',

  'settings.language': 'Language',
  'settings.theme': 'Theme',
  'settings.theme.dark': 'Dark',
  'settings.theme.light': 'Light',
  'settings.theme.system': 'System',
  'settings.language.ar': 'Arabic',
  'settings.language.en': 'English',

  'notif.push': 'Push Notifications',
  'notif.reminders': 'Subscription Reminders',
  'notif.content': 'Content Updates',
  'notif.announcements': 'Announcements',
  'notif.sound': 'Notification Sound',
};
